### ISSUE TITLE
快捷键修改

### ISSUE THREAD

**Issue by UltramarineSky** [Zuoqiu-Yingyi/siyuan-plugin-jupyter-client#17]
请问怎么修改快捷键啊，用`shift+enter`软换行时总是跳弹窗未找到有效块，看了下才发现是和jupyter的快捷键重复了

**Comment by Zuoqiu-Yingyi** [comment]
> 请问怎么修改快捷键啊，用`shift+enter`软换行时总是跳弹窗未找到有效块，看了下才发现是和jupyter的快捷键重复了

在思源设置-快捷键设置面板下方是修改所有插件快捷键的功能
