### ISSUE TITLE
请教怎么运行

### ISSUE THREAD

**Issue by luoxxib** [Zuoqiu-Yingyi/siyuan-plugin-jupyter-client#18]
插件已安装上了，无法新建会话，也不能运行代码块中的代码

**Comment by Zuoqiu-Yingyi** [comment]
请先参考插件的介绍, 创建会话前需要配置并连接 Jupyter 服务

**Comment by luoxxib** [comment]
![image](https://github.com/Zuoqiu-Yingyi/siyuan-plugin-jupyter-client/assets/9431773/546606fd-2e06-4d81-b227-599d7ddcfb04)
![image](https://github.com/Zuoqiu-Yingyi/siyuan-plugin-jupyter-client/assets/9431773/661ae81a-1419-41cb-b3fc-036fa92ee8df)
已经配置好了
![image](https://github.com/Zuoqiu-Yingyi/siyuan-plugin-jupyter-client/assets/9431773/ce799331-b132-46ef-baa5-62312489d5cf)
在哪里创建会话

**Comment by Zuoqiu-Yingyi** [comment]
> 在哪里创建会话

一个 jupyter 会话需要与一篇文档绑定, 因此在如下菜单中新建会话
`文档块菜单` > `插件` > `Jupyter 客户端` > `会话` > `会话设置`
![image](https://github.com/Zuoqiu-Yingyi/siyuan-plugin-jupyter-client/assets/49649786/9b2b827e-9853-40b9-89b7-58a981ee03e1)

**Comment by luoxxib** [comment]
谢谢，已经可以运行了

**Comment by jiewangjs** [comment]
我遇到下面的问题，好像一切都设置好了，但是run没有任何输出。调console看错误截图在下面，请问什么原因？
![image](https://github.com/Zuoqiu-Yingyi/siyuan-plugin-jupyter-client/assets/11204422/4871e25d-3d6c-4b7a-b6ec-f3927c66b0fa)

![image](https://github.com/Zuoqiu-Yingyi/siyuan-plugin-jupyter-client/assets/11204422/11d06323-ee8d-447d-b43e-6f67604f1d0f)

**Comment by jiewangjs** [comment]
还有就是，如果选新建会话的话，会有一个错误，不知道怎么解决？

![image](https://github.com/Zuoqiu-Yingyi/siyuan-plugin-jupyter-client/assets/11204422/a12a17b4-42a3-4b71-bca9-88d8deec5214)

**Comment by Zuoqiu-Yingyi** [comment]
<details>

> 我遇到下面的问题，好像一切都设置好了，但是run没有任何输出。调console看错误截图在下面，请问什么原因？
> ![image](https://private-user-images.githubusercontent.com/11204422/334638120-4871e25d-3d6c-4b7a-b6ec-f3927c66b0fa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcwNzYxMjgsIm5iZiI6MTcxNzA3NTgyOCwicGF0aCI6Ii8xMTIwNDQyMi8zMzQ2MzgxMjAtNDg3MWUyNWQtM2Q2Yy00YjdhLWI2ZWMtZjM5MjdjNjZiMGZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMwVDEzMzAyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY1N2JjYWVhYmFkMzdkMTVmMDhlODEzN2IxZmE0ZmQ2NzMxMzk5YjdkMjIzMzczZGEwMjQwZTI5NzI1N2ZkMTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9QtgrJSdVpu1IVBR5UxCK0sCudoZe73Z6gLnq9EK7P8)
> 
> ![image](https://private-user-images.githubusercontent.com/11204422/334637898-11d06323-ee8d-447d-b43e-6f67604f1d0f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcwNzYxMjgsIm5iZiI6MTcxNzA3NTgyOCwicGF0aCI6Ii8xMTIwNDQyMi8zMzQ2Mzc4OTgtMTFkMDYzMjMtZWU4ZC00NDdkLWI0M2UtNmY2NzYwNGYxZDBmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMwVDEzMzAyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNlOGZiMmMyNzdiZWVjZjVhOGM3YWUzMDBkYTRkMDE5OGFhMGIyZmRhYTI4YmNhMGZlM2ZjMjU4NjMzY2Y2NmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ROYxJx0e6vmkOaTG31DZ5aErQ6tnkDJ3QhzU7JzgJtI)
</details>

信息不足, 暂时无法定位到具体的原因, 看起来是启动内核失败造成的

**Comment by Zuoqiu-Yingyi** [comment]
<details>

> 还有就是，如果选新建会话的话，会有一个错误，不知道怎么解决？
> 
> ![image](https://private-user-images.githubusercontent.com/11204422/334639241-a12a17b4-42a3-4b71-bca9-88d8deec5214.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcwNzYxMjgsIm5iZiI6MTcxNzA3NTgyOCwicGF0aCI6Ii8xMTIwNDQyMi8zMzQ2MzkyNDEtYTEyYTE3YjQtNDJhMy00YjcxLWJjYTktODhkOGRlZWM1MjE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMwVDEzMzAyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIyZTRiZmY1YzAwMzc0ODNhNTZiMTdmODY5YTI3MDM3MjcxMzA1MDc4ZWUzN2QxYjk2OWUxMDI2NDEzYjA4MDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dMlqPSIX72BMo-bMsGVErIG0Ouh2OVQfGAiu06l0Lg8)

</details>

这个问题是最近出现的还是一直存在?

先参考一下用户指南, 设置一下 Jpyter 的如下选项试试

```python
c.ServerApp.allow_origin = '*'
```

**Comment by jiewangjs** [comment]
我这几天刚第一次试图用，从来没有成功。
c.ServerApp.allow_origin = '*' 
上面这个设置了。
jupyter notebook能够在浏览器中成功运行

**Comment by Zuoqiu-Yingyi** [comment]
> 我这几天刚第一次试图用，从来没有成功。 c.ServerApp.allow_origin = '*' 上面这个设置了。 jupyter notebook能够在浏览器中成功运行

哦, 那可能是所使用的库不兼容 Jupyter Notebook 服务造成的, 要不先试试能否正确连接 Jupyter Lab 服务

**Comment by jiewangjs** [comment]
每次一使用siyuan文档连接jupyter就在console报错
![image](https://github.com/Zuoqiu-Yingyi/siyuan-plugin-jupyter-client/assets/11204422/a855b21f-f95a-43fe-b9cd-dc3c253bee8b)
我这样的默认设置有问题吗？
![image](https://github.com/Zuoqiu-Yingyi/siyuan-plugin-jupyter-client/assets/11204422/df3d7693-1e59-46bb-b43f-da6b88fb5062)
听从你的建议，使用的是jupyter lab
我的token被我设置成了无，所以我的jupyter_lab_config.py里面就只加了一行
![image](https://github.com/Zuoqiu-Yingyi/siyuan-plugin-jupyter-client/assets/11204422/01e347c1-8be4-4d68-a647-85c10b0ec09c)
我粗浅的看上去，就是websocket连接不成功
![image](https://github.com/Zuoqiu-Yingyi/siyuan-plugin-jupyter-client/assets/11204422/81d652e2-939b-41b5-9349-f1e95d2e29e8)

**Comment by Zuoqiu-Yingyi** [comment]
要不设置一下 token 后试试
如果还是不行我也没办法了

**Comment by jiewangjs** [comment]
好的。谢谢！
