### ISSUE TITLE
怎么连接会话

### ISSUE THREAD

**Issue by weiyx2** [Zuoqiu-Yingyi/siyuan-plugin-jupyter-client#5]
在插件中，没有看到连接会话的选项

**Comment by Zuoqiu-Yingyi** [comment]
文档块菜单 > 插件 > Jupyter 客户端 > 会话 > 会话设置

**Comment by weiyx2** [comment]
<img width="1223" alt="image" src="https://github.com/Zuoqiu-Yingyi/siyuan-plugin-jupyter-client/assets/126885007/59936fa2-f3d2-4d3a-b692-895636cdf957">
感谢您的回答，但是我怎么在菜单中找不到会话设置在哪里

**Comment by Zuoqiu-Yingyi** [comment]
> <img alt="image" width="1223" src="https://user-images.githubusercontent.com/126885007/265673487-59936fa2-f3d2-4d3a-b692-895636cdf957.png"> 感谢您的回答，但是我怎么在菜单中找不到会话设置在哪里

这里菜单项重叠在一起了, 点击文档标题前面的文档块标试试

**Comment by weiyx2** [comment]
<img width="785" alt="image" src="https://github.com/Zuoqiu-Yingyi/siyuan-plugin-jupyter-client/assets/126885007/5a068f36-0ce8-4037-ace7-df1c3771a8a3">
还是没找到😭

**Comment by HowcanoeWang** [comment]
> <img alt="image" width="785" src="https://user-images.githubusercontent.com/126885007/265863449-5a068f36-0ce8-4037-ace7-df1c3771a8a3.png"> 还是没找到😭

我猜是这个，插件介绍里确实没讲清楚，也是折腾了很久才整明白

![image](https://github.com/Zuoqiu-Yingyi/siyuan-plugin-jupyter-client/assets/19968935/d8f27085-ca77-41e2-be8e-fd8a3566c698)

**Comment by weiyx2** [comment]
非常感谢🌹

**Comment by ghost** [comment]
请问为什么设置了token，运行了jupyter，已安装内核那还是没反应哇，\哭
![image](https://github.com/Zuoqiu-Yingyi/siyuan-plugin-jupyter-client/assets/68829841/3cd1302b-eb7d-4da0-a73f-c877f99f411f)

```python
#jupyter_notebook_config.py
c.ServerApp.allow_origin = '*'
c.IdentityProvider.token = 'qwertyuiop'
```

![image](https://github.com/Zuoqiu-Yingyi/siyuan-plugin-jupyter-client/assets/68829841/e240f8f0-9ca9-41b7-bfe5-3e7bb3590fed)

**Comment by Zuoqiu-Yingyi** [comment]
> 请问为什么设置了token，运行了jupyter，已安装内核那还是没反应哇，\哭

请检查是否打开了 `启用 Jupyter 客户端` 开关

**Comment by ghost** [comment]
打开了的
![image](https://github.com/Zuoqiu-Yingyi/siyuan-plugin-jupyter-client/assets/68829841/8ce1cd5a-b529-4d97-8e2f-7356e107f6f0)
![image](https://github.com/Zuoqiu-Yingyi/siyuan-plugin-jupyter-client/assets/68829841/f2bfb972-1b48-49b2-88f8-a7740a2d77ea)
是需要配合大佬的dark+使用吗

**Comment by Zuoqiu-Yingyi** [comment]
> 是需要配合大佬的dark+使用吗

不需要, 这个插件是独立的

关闭该开关后再打开试试
如果还是不行的话打开思源的开发者工具瞅瞅 Jupyter 服务相关的 API 请求是否成功
